### ISSUE TITLE
invalid builtin function: '@intToFloat'

### ISSUE THREAD

**Issue by jessbowers** [contextfreeinfo/tacana#1]
```
 % ./run.sh
explore-simple.zig:57:19: error: expected 1 argument, found 2
    const state = @ptrCast(*State, @alignCast(@alignOf(State), userdata));
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
explore-simple.zig:109:20: error: invalid builtin function: '@intToFloat'
    const aspect = @intToFloat(f32, size.x) / @intToFloat(f32, size.y);

```

Running on MacOS 13.5, zig `0.12.0-dev.64+b835fd90c`, `rustc 1.71.1`

**Comment by tjpalmer** [comment]
Hi, thanks for the report! I haven't tried Zig 0.12 yet. Looks like they are [changing int to float conversion](https://ziglang.org/documentation/master/#floatFromInt) in the new release vs what I've been using. Is it possible to be compatible with both? If not, can you try 0.11?

I usually keep multiple versions handy and use symlinks to switch back and forth. Maybe you prefer a different method for that.

**Comment by tjpalmer** [comment]
As a heads up, I expect the code will fail on Mac because I don't have a Mac to work out creating the surface. See these comments:

https://github.com/contextfreeinfo/taca/blob/9d948783a7870481ecd3a6b594dcfa91ed013d2d/src/webgpu.rs#L1175-L1176

**Comment by jessbowers** [comment]
I'll try 0.11 on Linux & see if I have better luck. It's a good example of what's possible with wasm  and desktop apps - thanks for sharing it!

**Comment by tjpalmer** [comment]
Latest demo code is on Zig 0.13, so I'll close this issue.
